apiVersion: v1
kind: Service
metadata:
    name: af-catalog
    labels:
        app: catalog
        tier: frontend
spec:
    type: NodePort
    ports:
        - port: 8080
    selector:
        app: catalog
        tier: frontend


