apiVersion: apps/v1
kind: Deployment
metadata:
    name: af-gateway
spec:
    selector:
        matchLabels:
            app: gateway
            tier: backend
    replicas: 1
    template:
        metadata:
            labels:
                app: gateway
                tier: backend
        spec:
            containers:
            - name: gateway
              image: smartcommunitylab/af-gateway
              ports:
                  - containerPort: 8080
