apiVersion: v1
kind: Service
metadata:
    name: af-gateway
    labels:
        app: gateway
        tier: backend
spec:
    type: NodePort
    ports:
    - port: 9000
      targetPort: 8080
    selector:
        app: gateway
        tier: backend


