apiVersion: v1
kind: Service
metadata:
    name: af-registry
    labels:
        app: registry
        tier: backend
spec:
    type: NodePort
    ports:
    - port: 8761
    selector:
        app: registry
        tier: backend

