apiVersion: apps/v1
kind: Deployment
metadata:
    name: af-registry
spec:
    selector:
        matchLabels:
            app: registry
            tier: backend
    replicas: 1
    template:
        metadata:
            labels:
                app: registry
                tier: backend
        spec:
            containers:
                - name: registry
                  image: smartcommunitylab/af-registry:prom
                  ports:
                  - containerPort: 8761
