apiVersion: v1
kind: Service
metadata:
    name: af-zipkin
    labels:
        app: zipkin
        tier: backend
spec:
    type: NodePort
    ports:
    - port: 9411
    selector:
        app: zipkin
        tier: backend 
